export const FETCH_CYCLE_INFO_BEGIN = 'FETCH_CYCLE_INFO_BEGIN';
export const FETCH_CYCLE_INFO_SUCCESS = 'FETCH_CYCLE_INFO_SUCCESS';
export const FETCH_CYCLE_INFO_FAILURE = 'FETCH_CYCLE_INFO_FAILURE';
export const CLEAR_CYCLE_INFO = 'CLEAR_CYCLE_INFO';